# Generated by Django 4.2.3 on 2023-08-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_my_choices_alter_product_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_choices',
            name='my_field',
            field=models.CharField(choices=[('a', 'Hola'), ('b', 'Hello'), ('c', 'Bonjour'), ('d', 'Boas')], max_length=5, null=True),
        ),
    ]
