# Generated by Django 4.2.3 on 2023-08-04 10:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_my_choices_my_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_choices',
            name='choice',
        ),
        migrations.AlterField(
            model_name='my_choices',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=10, null=True),
        ),
    ]
