# Generated by Django 4.2.3 on 2023-08-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_alter_my_choices_my_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MODEL',
        ),
    ]
