# Generated by Django 4.2.3 on 2023-08-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_delete_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MY_CHOICES',
        ),
        migrations.AddField(
            model_name='clothing',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.color'),
        ),
    ]
