# Generated by Django 4.2.3 on 2023-08-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_clothing_color_delete_my_choices_clothing_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
