# Generated by Django 4.2.3 on 2023-08-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0014_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
