# Generated by Django 4.2.3 on 2023-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0019_alter_color_name_alter_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countdown_target',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
