# Generated by Django 4.2.3 on 2023-08-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0023_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
    ]
