# Generated by Django 4.2.3 on 2023-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0026_alter_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=160),
        ),
    ]
