# Generated by Django 4.2.3 on 2023-08-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0027_alter_comments_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
