# Generated by Django 4.2.3 on 2023-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0029_cartt_cartitemm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemm',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
