# Generated by Django 4.2.3 on 2023-09-03 11:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0033_alter_comparedproduct_product_1_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comparedproduct',
            unique_together={('product_1', 'product_2', 'user')},
        ),
    ]
