# Generated by Django 4.2.3 on 2023-09-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0034_alter_comparedproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparedproduct',
            name='product_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='proj.product', unique=True),
        ),
        migrations.AlterField(
            model_name='comparedproduct',
            name='product_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='proj.product', unique=True),
        ),
    ]
