# Generated by Django 4.2.3 on 2023-09-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0035_alter_comparedproduct_product_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparedproduct',
            name='product_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='proj.product'),
        ),
        migrations.AlterField(
            model_name='comparedproduct',
            name='product_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='proj.product'),
        ),
    ]
