# Generated by Django 4.2.3 on 2023-09-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0042_address_coupon_order_orderproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_order',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
