# Generated by Django 4.2.3 on 2023-09-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0043_rename_cart_order_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cartt',
        ),
    ]
