# Generated by Django 4.2.3 on 2023-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0044_remove_orderproduct_cart_delete_cartt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
