# Generated by Django 4.2.3 on 2023-09-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0045_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
