# Generated by Django 4.2.3 on 2023-09-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0046_address_email_address_first_name_address_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
